### PR TITLE
Changed text

### PR DESCRIPTION
**Pull request by workwithAarohan**
Update Home page

### CODE REVIEW

**Comment by workwithAarohan** [comment]
@Sagar-Timalsena 
timle PracticesProjects vanne organization create gareko ho???

**Comment by Sagar-Timalsena** [comment]
ahh yrr ho..

**Review by Sagar-Timalsena — APPROVED** [review]
Home Page

**Comment by workwithAarohan** [comment]
Ok 

> Home Page



> ahh yrr ho..

**Comment by workwithAarohan** [comment]
Ok thank you sathi

**Pull request closed without merging**
